title: Hello, World.
description: Hi.
author: Migz Estrella
github: https://github.com/migzpogi
about: Software engineer that loves creating Python and Java applications, deploying them to cloud services such as AWS, and providing insights through data analytics. I also like mechanical keyboards.
disqus_shortname: helloworld
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/headshot.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/agusmakmun6"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/migzestrella"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/migzpogi"

share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/


per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
